import './globals.scss';

export const metadata = {
  title: 'FNBO Flex Scraper',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <link
        rel='manifest'
        href='/manifest.webmanifest'
        crossOrigin='use-credentials'
      />
      <meta
        name='theme-color'
        media='(prefers-color-scheme: light)'
        content='white'
      />
      <meta
        name='theme-color'
        media='(prefers-color-scheme: dark)'
        content='black'
      />
      <link rel='icon' href='/images/logo.png' crossOrigin='use-credentials' />
      <body>{children}</body>
    </html>
  );
}
